#!/usr/bin/perl

$arg = shift @ARGV;
if ($arg !~ m/^\d+$/) {
    die('specify card number');
}

$baseDir = __FILE__;
$baseDir =~ s/[^\/]*$//g;
if ($baseDir) {
    chdir $baseDir;
}

$path = $ENV{'HOME'} . '/.asoundrc';

if (-e $path) {
    open FH, $path or die("unable to open $path");
    $line = <FH>;
    close FH;
    if ($line !~ m/^#FROG/) {
        $str = <<EOF;
A config file at '$path' needs to be generated.

This file already exists, but was not generated by FROG.

Rename or delete this file, and then try again.
EOF
        system('frog', 'alert', $str);
        exit 1;
    }
}

open FH, ">$path" or die("unable to write $path");
print FH <<EOF;
#FROG hw:$arg
defaults.pcm.card $arg
defaults.ctl.card $arg
EOF
close FH;

system('touch', 'Config/menuBar.csv');

